;;; -*- Mode: Lisp; Package: user -*-
;;; toggle-gates.l --- toggle-gates.l の ni-autoload 用モジュール

;; Copyright (C) 2001-2005 OHKUBO Hiroshi <ohkubo@s53.xrea.com>

;; Author: OHKUBO Hiroshi <ohkubo@s53.xrea.com>
;; Time-stamp: <2005/10/08 10:50:53 +0900>

;; Description:
;;
;;     toggle-gates.l の ni-autoload 用モジュール
;;

; 起動時から使用するためrequireで読み込む
(require "toggle-gates")

;;; toggle-gates.l ends here
