;;; -*- Mode: Lisp; Package: user -*-
;;; treeview.l --- treeview.l の ni-autoload 用モジュール

;; Copyright (C) 2001-2005 OHKUBO Hiroshi <konata_o@hotmail.com>

;; Author: OHKUBO Hiroshi <konata_o@hotmail.com>
;; Time-stamp: <2005/02/16 18:27:45 +0900>

;; Description:
;;
;;     treeview.l の ni-autoload 用モジュール
;;

; 起動時から使用するため require で読み込む
(require "treeview/setup")

;;; treeview.l ends here
