#!/bin/sh

cat $1                                                             |
nkf -Se                                                            |
perl -ne 'printf "%s /%s/\n", $1, $2 if (/^([^!]+?)\t(.+?)\t.+$/)' |
skkdic-expr2                                                       |
skkdic-sort > $2

