;;; -*- Mode: Lisp; Package: user -*-
;;; toggle-gates.l --- toggle-gates.l の uninstall 用モジュール

;; Copyright (C) 2001-2005 OHKUBO Hiroshi <ohkubo@s53.xrea.com>

;; Author: OHKUBO Hiroshi <ohkubo@s53.xrea.com>
;; Time-stamp: <2005/10/08 10:51:32 +0900>

;; Description:
;;
;;     toggle-gates.l の uninstall 用モジュール
;;

(require "toggle-gates")
(ed::toggle-gates-uninstall)

;;; toggle-gates.l ends here
