git submodule add https://github.com/awasira/cp5022x.el .emacs.d/elisp/cp5022x
git submodule add https://github.com/auto-complete/auto-complete .emacs.d/elisp/auto-complete
git submodule add https://github.com/joodland/bm .emacs.d/elisp/bm
git submodule add https://github.com/m2ym/direx-el .emacs.d/elisp/direx-el
git submodule add https://github.com/m2ym/popwin-el .emacs.d/elisp/popwin-el
git submodule add https://github.com/magit/magit .emacs.d/elisp/magit
git submodule add https://github.com/magit/git-modes .emacs.d/elisp/git-modes
git submodule add https://github.com/hayamiz/twittering-mode .emacs.d/elisp/twittering-mode
git submodule add https://github.com/konr/tomatinho .emacs.d/elisp/tomatinho
git submodule add https://github.com/capitaomorte/yasnippet .emacs.d/elisp/yasnippet
git submodule add https://github.com/purcell/ac-slime .emacs.d/elisp/ac-slime
git submodule add https://github.com/brianjcj/auto-complete-clang .emacs.d/elisp/auto-complete-clang
git submodule add https://github.com/jixiuf/ajc-java-complete .emacs.d/elisp/ajc-java-complete
git submodule add https://github.com/nekop/yasnippet-java-mode .emacs.d/elisp/yasnippet-java-mode
git submodule add https://github.com/zenozeng/php-eldoc .emacs.d/elisp/php-eldoc
git submodule add https://github.com/zenozeng/css-eldoc .emacs.d/elisp/css-eldoc
git submodule add https://github.com/ejmr/php-mode .emacs.d/elisp/php-mode
git submodule add https://github.com/arnested/php-extras .emacs.d/elisp/php-extras
git submodule add https://github.com/echosa/phpplus-mode .emacs.d/elisp/phpplus-mode
git submodule add https://github.com/tetsujin/emacs-php-align .emacs.d/elisp/emacs-php-align
git submodule add https://github.com/taksatou/inf-php .emacs.d/elisp/inf-php
git submodule add https://github.com/yoshiki/yaml-mode .emacs.d/elisp/yaml-mode
git submodule add https://github.com/mcorde/geben-on-emacs .emacs.d/elisp/geben-on-emacs
git submodule add https://github.com/espenhw/malabar-mode .emacs.d/elisp/malabar-mode
git submodule add https://github.com/haskell/haskell-mode .emacs.d/elisp/haskell-mode
git submodule add https://github.com/jochu/clojure-mode .emacs.d/elisp/clojure-mode
git submodule add https://github.com/jochu/swank-clojure .emacs.d/elisp/swank-clojure
git submodule add https://github.com/naota/navi2ch .emacs.d/elisp/navi2ch
git submodule add https://github.com/fxbois/web-mode .emacs.d/elisp/web-mode
git submodule add https://github.com/emacs-helm/helm .emacs.d/elisp/helm
git submodule add https://github.com/emacs-helm/helm-ls-git .emacs.d/elisp/helm-ls-git
git submodule add https://github.com/emacs-helm/helm-descbinds .emacs.d/elisp/helm-descbinds
git submodule add https://github.com/jwiegley/org-mode .emacs.d/elisp/org-mode
git submodule add https://github.com/emacs-jp/japanese-holidays .emacs.d/elisp/japanese-holidays
