git submodule deinit .emacs.d/elisp/cp5022x
git submodule deinit .emacs.d/elisp/auto-complete
git submodule deinit .emacs.d/elisp/bm
git submodule deinit .emacs.d/elisp/direx-el
git submodule deinit .emacs.d/elisp/popwin-el
git submodule deinit .emacs.d/elisp/magit
git submodule deinit .emacs.d/elisp/git-modes
git submodule deinit .emacs.d/elisp/twittering-mode
git submodule deinit .emacs.d/elisp/tomatinho
git submodule deinit .emacs.d/elisp/yasnippet
git submodule deinit .emacs.d/elisp/ac-slime
git submodule deinit .emacs.d/elisp/auto-complete-clang
git submodule deinit .emacs.d/elisp/ajc-java-complete
git submodule deinit .emacs.d/elisp/yasnippet-java-mode
git submodule deinit .emacs.d/elisp/php-eldoc
git submodule deinit .emacs.d/elisp/css-eldoc
git submodule deinit .emacs.d/elisp/php-mode
git submodule deinit .emacs.d/elisp/php-extras
git submodule deinit .emacs.d/elisp/phpplus-mode
git submodule deinit .emacs.d/elisp/emacs-php-align
git submodule deinit .emacs.d/elisp/inf-php
git submodule deinit .emacs.d/elisp/yaml-mode
git submodule deinit .emacs.d/elisp/geben-on-emacs
git submodule deinit .emacs.d/elisp/malabar-mode
git submodule deinit .emacs.d/elisp/haskell-mode
git submodule deinit .emacs.d/elisp/clojure-mode
git submodule deinit .emacs.d/elisp/swank-clojure
git submodule deinit .emacs.d/elisp/navi2ch
git submodule deinit .emacs.d/elisp/web-mode
git submodule deinit .emacs.d/elisp/helm
git submodule deinit .emacs.d/elisp/helm-ls-git
git submodule deinit .emacs.d/elisp/helm-descbinds
git submodule deinit .emacs.d/elisp/org-mode
git submodule deinit .emacs.d/elisp/japanese-holidays
