git submodule add https://github.com/awasira/cp5022x.el.git .emacs.d/elisp/cp5022x
git submodule add https://github.com/auto-complete/auto-complete.git .emacs.d/elisp/auto-complete
git submodule add https://github.com/joodland/bm.git .emacs.d/elisp/bm
git submodule add https://github.com/m2ym/direx-el.git .emacs.d/elisp/direx-el
git submodule add https://github.com/m2ym/popwin-el.git .emacs.d/elisp/popwin-el
git submodule add https://github.com/magit/magit.git .emacs.d/elisp/magit
git submodule add https://github.com/magit/git-modes.git .emacs.d/elisp/git-modes
git submodule add https://github.com/hayamiz/twittering-mode.git .emacs.d/elisp/twittering-mode
git submodule add https://github.com/konr/tomatinho.git .emacs.d/elisp/tomatinho
git submodule add https://github.com/capitaomorte/yasnippet.git .emacs.d/elisp/yasnippet
git submodule add https://github.com/purcell/ac-slime.git .emacs.d/elisp/ac-slime
git submodule add https://github.com/brianjcj/auto-complete-clang.git .emacs.d/elisp/auto-complete-clang
git submodule add https://github.com/jixiuf/ajc-java-complete.git .emacs.d/elisp/ajc-java-complete
git submodule add https://github.com/nekop/yasnippet-java-mode.git .emacs.d/elisp/yasnippet-java-mode
git submodule add https://github.com/zenozeng/php-eldoc.git .emacs.d/elisp/php-eldoc
git submodule add https://github.com/zenozeng/css-eldoc.git .emacs.d/elisp/css-eldoc
git submodule add https://github.com/ejmr/php-mode.git .emacs.d/elisp/php-mode
git submodule add https://github.com/arnested/php-extras.git .emacs.d/elisp/php-extras
git submodule add https://github.com/echosa/phpplus-mode.git .emacs.d/elisp/phpplus-mode
git submodule add https://github.com/tetsujin/emacs-php-align.git .emacs.d/elisp/emacs-php-align
git submodule add https://github.com/taksatou/inf-php.git .emacs.d/elisp/inf-php
git submodule add https://github.com/yoshiki/yaml-mode.git .emacs.d/elisp/yaml-mode
git submodule add https://github.com/mcorde/geben-on-emacs.git .emacs.d/elisp/geben-on-emacs
git submodule add https://github.com/espenhw/malabar-mode.git .emacs.d/elisp/malabar-mode
git submodule add https://github.com/haskell/haskell-mode.git .emacs.d/elisp/haskell-mode
git submodule add https://github.com/jochu/clojure-mode.git .emacs.d/elisp/clojure-mode
git submodule add https://github.com/jochu/swank-clojure.git .emacs.d/elisp/swank-clojure
git submodule add https://github.com/naota/navi2ch.git .emacs.d/elisp/navi2ch
git submodule add https://github.com/fxbois/web-mode.git .emacs.d/elisp/web-mode
git submodule add https://github.com/emacs-helm/helm.git .emacs.d/elisp/helm
git submodule add https://github.com/emacs-helm/helm-ls-git.git .emacs.d/elisp/helm-ls-git
git submodule add https://github.com/emacs-helm/helm-descbinds.git .emacs.d/elisp/helm-descbinds
git submodule add https://orgmode.org/org-mode.git .emacs.d/elisp/org-mode
git submodule add https://github.com/emacs-jp/japanese-holidays.git .emacs.d/elisp/japanese-holidays
