;;; -*- mode: emacs-lisp; coding: utf-8; indent-tabs-mode: nil -*-
;; URL リスト
(when (boundp 'newsticker-url-list)
  (setq newsticker-url-list
        '(("Linux.com" "http://www.linux.com/feature?theme=rss")
          ("Linux Journal" "http://blip.tv/linux-journal/rss/itunes")
          ("Linuxメモ" "http://toybox.tea-nifty.com/linux/rss.xml")
          ("SourceForge.JP Magazine" "http://sourceforge.jp/magazine/rss")
          ("【Opensource】SourceForge.JP Magazine" "http://sourceforge.jp/magazine/opensource/rss")
          ("【News】SourceForge.JP Magazine" "http://sourceforge.jp/magazine/news/rss")
          ("【Enterprise】SourceForge.JP Magazine" "http://sourceforge.jp/magazine/enterprise/rss")
          ("【Linux】スラッシュドット・ジャパン" "http://slashdot.jp/linux.rss")
          ("日本Linux協会blog" "http://feeds.japan.zdnet.com/zdnet/blog/jla")
          ("【Linux】ITpro オープンソース" "http://itpro.nikkeibp.co.jp/rss/oss.rdf")
          ("＠IT Linux ＆ OSSフォーラム" "http://www.atmarkit.co.jp/rss/flinux/rss.xml")
          ("スタート ユア エンジン" "http://japan.internet.com/rss/rdf/column90new.rdf")
          ("CNN Topstory" "http://rss.cnn.com/rss/edition.rss")
          ("デイリーポータルＺ" "http://portal.nifty.com/rss/headline.rdf")
          ("asahi.com" "http://www3.asahi.com/rss/index.rdf")
          ("スラッシュドット・ジャパン" "http://slashdot.jp/slashdotjp.rss")
          ("ITmedia 速報" "http://rss.itmedia.co.jp/rss/2.0/news_bursts.xml")
          ("ITmedia 国内" "http://rss.itmedia.co.jp/rss/2.0/news_domestic.xml")
          ("ITmedia 海外" "http://rss.itmedia.co.jp/rss/2.0/news_foreign.xml")
          ("ITmedia 科学" "http://rss.itmedia.co.jp/rss/2.0/news_technology.xml")
          ("ITmedia ネット" "http://rss.itmedia.co.jp/rss/2.0/news_nettopics.xml")
          ("ITmedia セキュリティ" "http://rss.itmedia.co.jp/rss/2.0/news_security.xml")
          ("ITmedia 製品" "http://rss.itmedia.co.jp/rss/2.0/news_products.xml")
          ("日経BP" "http://feed.nikkeibp.co.jp/rss/nikkeibp/index.rdf")
          ("CNET Japan" "http://japan.cnet.com/rss/index.rdf")
          ("M$ セキュリティ" "http://www.microsoft.com/japan/technet/rss/articles_rss.aspx?category=029")
          ("404 Blog Not Found" "http://blog.livedoor.jp/dankogai/index.rdf")
          ("結城浩の日記" "http://www.hyuki.com/d/rss.xml")
          ("場末Ｐ科病院の精神科医のblog" "http://blog.livedoor.jp/beziehungswahn/index.rdf")
          ("2chまとめサイトのまとめ" "http://labo.tv/2chnews/index.xml")
          ("無題ドキュメント" "http://www.mudainodocument.com/index.rdf")
          ("アルファルファモザイク" "http://alfalfalfa.com/index.rdf")
          ("痛いニュース(ﾉ∀`)" "http://blog.livedoor.jp/dqnplus/index.rdf")
          ("【2ch】ニュー速クオリティ" "http://news4vip.livedoor.biz/index.rdf")
          ("【2ch】コピペ情報局" "http://news.2chblog.jp/index.rdf")
          ("ニュー投" "http://newtou.info/rss.xml")
          ("ニュース2ちゃんねる" "http://news020.blog13.fc2.com/?xml")
          ("常識的に考えた" "http://blog.livedoor.jp/jyoushiki43/atom.xml")
          ("Hyper News 2ch" "http://hypernews.2chblog.jp/atom.xml")
          ("watch@2チャンネル" "http://watch2ch.2chblog.jp/index.rdf")
          ("ピカピカニュース2ch" "http://pika2.livedoor.biz/index.rdf")
          ("まとめたニュース" "http://matometanews.com/index.rdf")
          ("(´A｀)＜咳をしてもゆとり" "http://yutori2ch.blog67.fc2.com/?xml")
          ("あじゃじゃしたー" "http://blog.livedoor.jp/chihhylove/index.rdf")
          ("ガハろぐNewsヽ(･ω･)/ｽﾞｺｰ" "http://gahalog.2chblog.jp/atom.xml")
          ("まめ速" "http://mamesoku.com/index.rdf"))))

