;;; -*- mode: emacs-lisp; coding: utf-8; indent-tabs-mode: nil -*-
(when (and (boundp 'org-feed-alist)
           (fboundp 'find-directory))
  (let ((org-dir (concat (file-name-as-directory
                          (catch 'found (find-directory "org"))) "feeds.org")))
    (setq org-feed-alist
          `(("Linux.com" "http://www.linux.com/feature?theme=rss" ,org-dir "Linux")
            ("Linux Journal" "http://blip.tv/linux-journal/rss/itunes" ,org-dir "Linux")
            ("Linuxメモ" "http://toybox.tea-nifty.com/linux/rss.xml" ,org-dir "Linux")
            ("SourceForge.JP Magazine" "http://sourceforge.jp/magazine/rss" ,org-dir "Linux")
            ("【Opensource】SourceForge.JP Magazine" "http://sourceforge.jp/magazine/opensource/rss" ,org-dir "Linux")
            ("【News】SourceForge.JP Magazine" "http://sourceforge.jp/magazine/news/rss" ,org-dir "Linux")
            ("【Enterprise】SourceForge.JP Magazine" "http://sourceforge.jp/magazine/enterprise/rss" ,org-dir "Linux")
            ("【Linux】スラッシュドット・ジャパン" "http://slashdot.jp/linux.rss" ,org-dir "Linux")
            ("日本Linux協会blog" "http://feeds.japan.zdnet.com/zdnet/blog/jla" ,org-dir "Linux")
            ("【Linux】ITpro オープンソース" "http://itpro.nikkeibp.co.jp/rss/oss.rdf" ,org-dir "Linux")
            ("＠IT Linux ＆ OSSフォーラム" "http://www.atmarkit.co.jp/rss/flinux/rss.xml" ,org-dir "Linux")
            ("スタート ユア エンジン" "http://japan.internet.com/rss/rdf/column90new.rdf" ,org-dir "Linux")
            ("CNN Topstory" "http://rss.cnn.com/rss/edition.rss" ,org-dir "News")
            ("デイリーポータルＺ" "http://portal.nifty.com/rss/headline.rdf" ,org-dir "News")
            ("asahi.com" "http://www3.asahi.com/rss/index.rdf" ,org-dir "News")
            ("スラッシュドット・ジャパン" "http://slashdot.jp/slashdotjp.rss" ,org-dir "News")
            ("ITmedia 速報" "http://rss.itmedia.co.jp/rss/2.0/news_bursts.xml" ,org-dir "News")
            ("ITmedia 国内" "http://rss.itmedia.co.jp/rss/2.0/news_domestic.xml" ,org-dir "News")
            ("ITmedia 海外" "http://rss.itmedia.co.jp/rss/2.0/news_foreign.xml" ,org-dir "News")
            ("ITmedia 科学" "http://rss.itmedia.co.jp/rss/2.0/news_technology.xml" ,org-dir "News")
            ("ITmedia ネット" "http://rss.itmedia.co.jp/rss/2.0/news_nettopics.xml" ,org-dir "News")
            ("ITmedia セキュリティ" "http://rss.itmedia.co.jp/rss/2.0/news_security.xml" ,org-dir "News")
            ("ITmedia 製品" "http://rss.itmedia.co.jp/rss/2.0/news_products.xml" ,org-dir "News")
            ("日経BP" "http://feed.nikkeibp.co.jp/rss/nikkeibp/index.rdf" ,org-dir "News")
            ("CNET Japan" "http://japan.cnet.com/rss/index.rdf" ,org-dir "News")
            ("M$ セキュリティ" "http://www.microsoft.com/japan/technet/rss/articles_rss.aspx?category=029" ,org-dir "News")
            ("404 Blog Not Found" "http://blog.livedoor.jp/dankogai/index.rdf" ,org-dir "Blog")
            ("結城浩の日記" "http://www.hyuki.com/d/rss.xml" ,org-dir "Blog")))))
