* Calendar/Diary

** 日／週／月／年単位の移動

カレンダー内を移動するコマンドはテキスト内を移動するコマンドに対比でき
ます.  日, 週, 月, 年を単位として前後に移動できます.

`C-f'
     1日後にポイントを進める（`calendar-forward-day'）.
`C-b'
     1日前にポイントを戻す（`calendar-backward-day'）.
`C-n'
     1週間後にポイントを進める（`calendar-forward-week'）.
`C-p'
     1週間前にポイントを戻す（`calendar-backward-week'）.
`M-}'
     1か月後にポイントを進める（`calendar-forward-month'）.
`M-{'
     1か月前にポイントを戻す（`calendar-backward-month'）.
`C-x ]'
     1年後にポイントを進める（`calendar-forward-year'）.
`C-x ['
     1年前にポイントを戻す（`calendar-backward-year'）.

** 週／月／年の始めと終り

週（または, 月, 年）というのは, 単に1日1日が集まったものではありません. 
週（月, 年）は特定の日で始まると考えます.  そこで, カレンダー
（calendar）モードには, 週, 月, 年の始めや終りに移動するコマンドがあり
ます.

`C-a'
     週の始めにポイントを移動する（`calendar-beginning-of-week'）.
`C-e'
     週の終りにポイントを移動する（`calendar-end-of-week'）.
`M-a'
     月の始めにポイントを移動する（`calendar-beginning-of-month'）.
`M-e'
     月の終りにポイントを移動する（`calendar-end-of-month'）.
`M-<'
     年の始めにポイントを移動する（`calendar-beginning-of-year'）.
`M->'
     年の終りにポイントを移動する（`calendar-end-of-year'）.

** 特定の日付

カレンダー（calendar）モードには, さまざまな方法で指定した特定の日付へ
移動するコマンドがあります.

`g d'
     指定した日付へポイントを移動する（`calendar-goto-date'）.
`o'
     指定した月をカレンダーの中央月にする（`calendar-other-month'）.
`.'
     ポイントを今日の日付に移動する（`calendar-goto-today'）.

** カレンダーのスクロール

見えている範囲を越えて移動するとカレンダーは自動的にスクロールします. 
手動でスクロールすることもできます.  カレンダーを表示しているウィンド
ウでは, 長い長い紙に月を印刷したものの一部が見えているのだと考えてくだ
さい.  カレンダーをスクロールするとは, 新しい月が見えるようにこの紙を
動かすことに相当します.

`C-x <'
     カレンダーを1か月後にスクロールする（`scroll-calendar-left'）.
`C-x >'
     カレンダーを1か月前にスクロールする（`scroll-calendar-right'）.
`C-v'
`NEXT'
     カレンダーを3か月後にスクロールする
     （`scroll-calendar-left-three-months'）.
`M-v'
`PRIOR'
     カレンダーを3か月前にスクロールする
     （`scroll-calendar-right-three-months'）.

** 日数計算

`M-='
     カレントリージョン内の日数を表示する
     （`calendar-count-days-region'）.

** その他のカレンダーコマンド

`p d'
     通年日（1年のうちの何日目の日か）を表示する
     （`calendar-print-day-of-year'）.
`C-c C-l'
     カレンダーを表示しているウィンドウを再表示する（`redraw-calendar'）.
`SPC'
     別のウィンドウをスクロールする（`scroll-other-window'）.
`q'
     カレンダーから抜ける（`exit-calendar'）.

** LaTeXカレンダー
g
カレンダーLaTeXコマンドは, カレンダーを印刷するLaTeXコードのバッファに
作成します.  使用するコマンドに依存して, ポイント位置の日, 週, 月, 年
のいずれかを含んだカレンダーを印刷できます.

`t m'
     1か月分のカレンダーを生成する（`cal-tex-cursor-month'）.
`t M'
     横づかいで1か月分のカレンダーを生成する
     （`cal-tex-cursor-month-landscape'）.
`t d'
     1日分のカレンダーを生成する（`cal-tex-cursor-day'）.
`t w 1'
     1週間分の1ページのカレンダーを生成する（`cal-tex-cursor-week'）.
`t w 2'
     1週間分の2ページのカレンダーを生成する（`cal-tex-cursor-week2'）.
`t w 3'
     1週間分のISOスタイルのカレンダーを生成する
     （`cal-tex-cursor-week-iso'）.
`t w 4'
     月曜から始まる1週間分のカレンダーを生成する
     （`cal-tex-cursor-week-monday'）.
`t f w'
     ファイロファックス（システム手帳）スタイルの見開き2週間分のカレン
     ダーを生成する（`cal-tex-cursor-filofax-2week'）.
`t f W'
     ファイロファックス（システム手帳）スタイルの見開き1週間分のカレン
     ダーを生成する（`cal-tex-cursor-filofax-week'）.
`t y'
     1年分のカレンダーを生成する（`cal-tex-cursor-year'）.
`t Y'
     横づかいで1年分のカレンダーを生成する
     （`cal-tex-cursor-year-landscape'）.
`t f y'
     ファイロファックス（システム手帳）スタイルの1年分のカレンダーを生
     成する（`cal-tex-cursor-filofax-year'）.

** 祝祭日

Emacsのカレンダーはすべての祝祭日を把握しており, それらをカレンダーに
表示できます.

`h'
     選択された日付の祝祭日を表示する（`calendar-cursor-holidays'）.
`Mouse-2 Holidays'
     マウスでクリックした日付の祝祭日を表示する.
`x'
     カレンダーウィンドウの祝祭日に印を付ける
     （`mark-calendar-holidays'）.
`u'
     カレンダーウィンドウの印を消す（`calendar-unmark'）.
`a'
     表示中の3か月分のカレンダーのすべての祝祭日を別のウィンドウに表示
     する（`list-calendar-holidays'）.
`M-x holidays'
     今日を中心とした3か月間のすべての祝祭日を別のウィンドウに表示する.
`M-x list-holidays'
     指定した範囲の年の祝祭日を別のウィンドウに表示する.

** 日出入時刻

カレンダーの特別なコマンドで, 任意の日付の日出入時刻を2分以内の精度で
調べられます.

`S'
     選択した日付の日出入時刻を表示する（`calendar-sunrise-sunset'）.
`Mouse-2 Sunrise/Sunset'
     クリックした日付の日出入時刻を表示する.
`M-x sunrise-sunset'
     今日の日出入時刻を表示する.
`C-u M-x sunrise-sunset'
     指定した日付の日出入時刻を表示する

** 朔弦望（新月, 上弦, 満月, 下弦）

以下のコマンドは, 朔弦望（新月, 上弦, 満月, 下弦）の日付と時刻を表示し
ます.  これらの機能は, 『朔弦望に依存する』問題をデバッグするときに重
宝します.

`M'
     表示してある3か月間の朔弦望の日付／時刻の一覧を表示する
     （`calendar-phases-of-moon'）.
`M-x phases-of-moon'
     今日を中央にした3か月間の朔弦望の日付／時刻の一覧を表示する.

** 他の暦への変換

以下のコマンドは選択した日（ポイントがある日）を他の暦で表示します.

`Mouse-2  Other Calendars'
     クリックした日が, 他のさまざまな暦ではどうなるかを表示する.
`p c'
     選択した日をISO商用暦の日付で表示する（`calendar-print-iso-date'）.
`p j'
     選択した日をユリウス暦の日付で表示する
     （`calendar-print-julian-date'）.
`p a'
     選択した日を天文通算日（ユリウス日）で表示する
     （`calendar-print-astro-day-number'）.
`p h'
     選択した日をヘブライ暦の日付で表示する
     （`calendar-print-hebrew-date'）.
`p i'
     選択した日をイスラム暦の日付で表示する
     （`calendar-print-islamic-date'）.
`p f'
     選択した日をフランス革命暦の日付で表示する
     （`calendar-print-french-date'）.
`p C'
     選択した日を中国暦の日付で表示する（`calendar-print-chinese-date'）.
`p k'
     選択した日をコプト暦の日付で表示する
     （`calendar-print-coptic-date'）.
`p e'
     選択した日をエチオピア暦の日付で表示する
     （`calendar-print-ethiopic-date'）.
`p p'
     選択した日をペルシア暦の日付で表示する
     （`calendar-print-persian-date'）.
`p m'
     選択した日をマヤ暦の日付で表示する（`calendar-print-mayan-date'）.

** 他の暦からの変換

Emacsが扱える暦で日付を指定して, カレンダーの対応する日に移動できます. 
本節では, マヤ暦を除く暦でこれを行うコマンドを説明します.  マヤ暦につ
いては, これに続く節を参照してください.

`g c'
     ISO商用暦で指定した日付に移動する（`calendar-goto-iso-date'）.
`g j'
     ユリウス暦で指定した日付に移動する（`calendar-goto-julian-date'）.
`g a'
     天文通算日（ユリウス日）で指定した日付に移動する
     （`calendar-goto-astro-day-number'）.
`g h'
     ヘブライ暦で指定した日付に移動する（`calendar-goto-hebrew-date'）.
`g i'
     イスラム暦で指定した日付に移動する（`calendar-goto-islamic-date'）.
`g f'
     フランス革命暦で指定した日付に移動する
     （`calendar-goto-french-date'）.
`g C'
     中国暦で指定した日付に移動する（`calendar-goto-chinese-date'）.
`g p'
     ペルシア暦で指定した日付に移動する（`calendar-goto-persian-date'）.
`g k'
     コプト暦で指定した日付に移動する（`calendar-goto-coptic-date'）.
`g e'
     エチオピア暦で指定した日付に移動する
     （`calendar-goto-ethiopic-date'）.

** マヤ暦からの変換

以下はマヤ暦で日付を指定する方法です.

`g m l'
     ロングカウント暦で指定した日付に移動する
     （`calendar-goto-mayan-long-count-date'）.
`g m n t'
     ゾルキン暦のつぎの周期の日に進む（`calendar-next-tzolkin-date'）.
`g m p t'
     ゾルキン暦のまえの周期の日に戻る
     （`calendar-previous-tzolkin-date'）.
`g m n h'
     ハアブ暦のつぎの周期の日に進む（`calendar-next-haab-date'）.
`g m p h'
     ハアブ暦のまえの周期の日に戻る（`calendar-previous-haab-date'）.
`g m n c'
     マヤのカレンダーラウンドのつぎの周期の日に進む
     （`calendar-next-calendar-round-date'）.
`g m p c'
     マヤのカレンダーラウンドのまえの周期の日に戻る
     （`calendar-previous-calendar-round-date'）.

** 日誌項目の表示コマンド

いったん`~/diary'ファイルを作成しておけば, カレンダーを使ってこれを眺
めることができます.  また, カレンダー（calendar）モードの外からでも, 
今日の予定を参照できます.

`d'
     選択した日付のすべての日誌項目を表示する（`view-diary-entries'）.
`Mouse-2 Diary'
     クリックした日付のすべての日誌項目を表示する.
`s'
     日誌ファイル全体を表示する（`show-all-diary-entries'）.
`m'
     日誌項目が登録されているすべての日付に印を付ける
     （`mark-diary-entries'）.
`u'
     カレンダーウィンドウの印を消す（`calendar-unmark'）.
`M-x print-diary-entries'
     現在表示している日誌項目をそのまま印刷する.
`M-x diary'
     今日の日付の日誌項目すべてを表示する.
`M-x diary-mail-entries'
     これからの予定を自分自身にメイルする.

** 日誌への追加コマンド

カレンダー（calendar）モードの中には, 日誌の項目を作成するコマンドがい
くつかあります.

`i d'
     選択した日に日誌項目を追加する（`insert-diary-entry'）.
`i w'
     選択した曜日に日誌項目を追加する（`insert-weekly-diary-entry'）.
`i m'
     選択した月の日に日誌項目を追加する（`insert-monthly-diary-entry'）.
`i y'
     選択した年の日に日誌項目を追加する（`insert-yearly-diary-entry'）.

** 特別な日誌項目

カレンダーの日付に基づいて項目を追加する以外に, 毎年の記念日などを表す
"S式項目"（sexp entries）を日誌ファイルに入れることができます.  これら
の項目は, Emacsが日誌ファイルを読み込むときにLisp式（S式, sexp）を評価
することに基づいています.  S式項目では日付のかわりに, `%%'に続けて括弧
で括ったLisp式があります.  Lisp式が項目を適用する日付を決定します.

カレンダー（calendar）モードには, よく使われるS式項目を追加するコマン
ドがあります.

`i a'
     指定した日付の毎年の記念日の日誌項目を追加する
     （`insert-anniversary-diary-entry'）.
`i b'
     カレントリージョンに対してブロック日誌項目を追加する
     （`insert-block-diary-entry'）.
`i c'
     指定した日から始まる定期的に巡ってくる日誌項目を追加する
     （`insert-cyclic-diary-entry'）.
