* キーバインド

    A.1 すべてのモードで共通のキーバインド
    A.2 List モードでのキーバインド
    A.3 Board 系モード共通のキーバインド
    A.4 Board モードでのキーバインド
    A.5 Bookmark モードでのキーバインド
    A.6 Article モードでのキーバインド
    A.7 Message モードでのキーバインド
    A.8 Message モードでのアスキーアート一覧


** A.1 すべてのモードで共通のキーバインド

以下のキーバインドはすべてのモードで使用できる。ただし、モードで上書き されている場合はそちらに従う。

C-c C-f
    navi2ch-find-file スレのログファイルまたはログファイルが保存され ているディレクトリを指定

C-c C-t
    navi2ch-toggle-offline オフライン・オンラインの切り替え

C-c C-u
    navi2ch-goto-url 指定した URL の板・スレを表示

C-c C-v
    navi2ch-version Navi2ch のバージョンをミニバッファに表示

C-c C-o
    navi2ch-message-jump-to-message-buffer レスを書いてる途中なら、 レスを書くバッファと書き込むスレ/板のバッファに切り替え

C-c C-l
    navi2ch-be2ch-toggle-login Be@2chへのログイン状態の切り替え

C-c C-s
    navi2ch-search-web Web を使ったスレッドの検索

Message モード以外では以下のキーバインドも使える。ただし、モードで上書 きされている場合はそちらに従う。

1
    navi2ch-one-pane 1ペイン表示に切り替え

2
    navi2ch-two-pane 2ペイン表示に切り替え

3
    navi2ch-three-pane 3ペイン表示に切り替え

<
    beginning-of-buffer バッファの最初に移動

>
    navi2ch-end-of-buffer バッファの最後に移動

B
    navi2ch-bookmark-goto-bookmark Bookmark モードを表示

g
    navi2ch-goto-board 指定した板を表示

G
    navi2ch-goto-board 指定した板を表示

n
    next-line 次の行に移動

p
    previous-line 前の行に移動

t
    navi2ch-toggle-offline オフライン・オンラインの切り替え

V
    navi2ch-version Navi2ch のバージョンをミニバッファに表示


** A.2 List モードでのキーバインド

RET
    navi2ch-list-select-current-board 板を表示

q
    navi2ch-exit Navi2ch を終了

z
    navi2ch-suspend Navi2ch を中断

s
    navi2ch-list-sync 板リストを再読み込み

SPC
    navi2ch-list-select-current-board 板を表示

DEL
    scroll-down 下にスクロール

BS
    scroll-down 下にスクロール

a
    navi2ch-list-add-bookmark 板をブックマークに登録

b
    navi2ch-list-toggle-bookmark ブックマークと板リストの表示を切り替え

[mouse-2]
    navi2ch-list-mouse-select 板を表示

/
    navi2ch-list-toggle-open 板リストの開閉

[
    navi2ch-list-open-all-category すべての板リストを開く

]
    navi2ch-list-close-all-category すべての板リストを閉じる

D
    navi2ch-list-delete-global-bookmark グローバルブックマークを削除

C
    navi2ch-list-change-global-bookmark グローバルブックマークを編集

?
    navi2ch-list-search 検索

e
    navi2ch-list-expire 古いキャッシュファイルを削除する


** A.3 Board 系モード共通のキーバインド

RET
    navi2ch-bm-select-article スレを表示

[mouse-2]
    navi2ch-bm-select-article スレを表示

SPC
    navi2ch-bm-select-article-or-scroll-up スレを表示 (すでに表示し ているスレならばスレ画面を上にスクロール)

.
    navi2ch-bm-display-article スレを表示 (カーソルはスレに移動しな い)

i
    navi2ch-bm-fetch-article スレを更新

e
    navi2ch-bm-textize-article スレをテキストで保存

DEL
    navi2ch-bm-select-article-or-scroll-down スレを表示 (すでに表示 しているスレならばスレ画面を下にスクロール)

BS
    navi2ch-bm-select-article-or-scroll-down スレを表示 (すでに表示 しているスレならばスレ画面を下にスクロール)

n
    navi2ch-bm-next-line 次の行に移動

p
    navi2ch-bm-previous-line 前の行に移動

U
    navi2ch-board-show-url 板またはスレの URL をコピー、または板を ブラウザで表示

l
    navi2ch-bm-view-logo 板のロゴを表示

A
    navi2ch-board-add-global-bookmark グローバルブックマークに登録

q
    navi2ch-bm-exit 板を閉じる

S
    navi2ch-bm-sort スレをソート

?
    navi2ch-bm-search 検索

C-c C-m
    navi2ch-message-pop-message-buffer 書き込みのとき書き込み画面に 戻る

R
C-c C-r
    navi2ch-bm-remove-article スレの情報 (取得した .dat ファイルや既読情報など) を消す

C-o
    navi2ch-bm-save-dat-file .dat ファイルを保存

I
    navi2ch-bm-fetch-maybe-new-articles 更新されている可能性のあるスレをすべて更新

*
    navi2ch-bm-mark スレにマークをつける

u
    navi2ch-bm-unmark スレのマークを解除

m r
    navi2ch-bm-mark-region 選択領域のスレにマークをつける

m a
    navi2ch-bm-mark-all すべてのスレにマークをつける

m A
    navi2ch-bm-add-global-bookmark-mark-article マークしたスレをグ ローバルブックマークに登録

m .
    navi2ch-bm-display-mark-article マークしたスレを表示

m i
    navi2ch-bm-fetch-mark-article マークしたスレを更新

m e
    navi2ch-bm-textize-mark-article マークしたスレをテキストで保存

m m
    navi2ch-bm-mark-marks ある状態 (VCU) になっているスレをマーク

m ?
    navi2ch-bm-mark-by-query 正規表現にマッチするスレを問い合わせつ つマーク (という動作だと思う)

m b
    navi2ch-bm-add-bookmark-mark-article マークしたスレをローカルブッ クマークに登録

m R
    navi2ch-bm-remove-mark-article マークしたスレの情報 (取得した .dat ファイルや既読情報など) を消す


** A.4 Board モードでのキーバインド

Board 系モード共通のキーバインドも参照。See section A.3 Board 系モード共通のキーバインド.

s
    navi2ch-board-sync 板を再読み込み

r
    navi2ch-board-select-view-range スレの表示数を変更

a
    navi2ch-board-add-bookmark 板のブックマークにスレを登録

d
    navi2ch-board-hide-article スレを隠す

h
    navi2ch-board-toggle-hide 隠したスレを表示

+
    navi2ch-board-toggle-updated 更新されたスレのみ表示

b
    navi2ch-board-toggle-bookmark ブックマークを表示

w
    navi2ch-board-write-message スレを立てる

ESC e
    navi2ch-board-expire 古いキャッシュファイルを削除する

m d
    navi2ch-board-hide-mark-article マークしたスレを隠す


** A.5 Bookmark モードでのキーバインド

Board 系モード共通のキーバインドも参照。See section A.3 Board 系モード共通のキーバインド.

D
    navi2ch-bookmark-delete ブックマークを削除

d
    navi2ch-bookmark-cut ブックマークをカットし、キルリングに追加

C-k
    navi2ch-bookmark-cut ブックマークをカットし、キルリングに追加

C-y
    navi2ch-bookmark-yank キルリングからブックマークを張り付け

o
    navi2ch-bookmark-move 別のブックマークに移動

O
    navi2ch-bookmark-copy 別のブックマークにコピー

m d
    navi2ch-bookmark-cut-mark-article マークしたスレをカットし、キルリングに追加

m o
    navi2ch-bookmark-move-mark-article マークしたスレを別のブックマークに移動

s
    navi2ch-bookmark-sync ブックマークバッファを最新の情報に更新

X
    navi2ch-bookmark-remember-order ブックマークの現在のスレの並び順を記憶

S
    navi2ch-bookmark-sort スレをソート


** A.6 Article モードでのキーバインド

q
    navi2ch-article-exit スレを閉じる

Q
    navi2ch-article-goto-current-board そのスレのある板を表示

s
    navi2ch-article-sync スレを再読み込み

S
    navi2ch-article-sync-disable-diff スレを差分なしで読み込み

r
    navi2ch-article-redraw-range レスの表示数を変更

j
    navi2ch-article-few-scroll-up 一行上へスクロール

k
    navi2ch-article-few-scroll-down 一行下へスクロール

SPC
    navi2ch-article-scroll-up 一画面上へスクロール

DEL
    navi2ch-article-scroll-down 一画面下へスクロール

BS
    navi2ch-article-scroll-down 一画面下へスクロール

w
    navi2ch-article-write-message レスを書き込む

W
    navi2ch-article-write-sage-message レスを sage で書き込む

RET
    navi2ch-article-select-current-link リンクを表示

[mouse-2]
    navi2ch-article-mouse-select リンクをマウスで選択

g
    navi2ch-article-goto-number-or-board 指定したレスか板にジャンプ

l
    navi2ch-article-pop-point 記憶されたカーソル位置にジャンプ

L
    navi2ch-article-pop-poped-point 記憶したカーソル位置に逆方向に ジャンプ

m
    navi2ch-article-push-point 現在のカーソル位置を記憶

U
    navi2ch-article-show-url スレ・特定のレス・板の URL をコピー、 あるいはブラウザで表示

.
    navi2ch-article-redisplay-current-message カーソルのあるレスを バッファの一番上に移動

p
    navi2ch-article-previous-message ひとつ前のレスに移動

n
    navi2ch-article-next-message 次のレスに移動

P
    navi2ch-article-through-previous ひとつ上のスレに移動

N
    navi2ch-article-through-next ひとつ下のスレに移動

SHIFT TAB
    navi2ch-article-previous-link ひとつ前のリンクに移動

ESC TAB
    navi2ch-article-previous-link ひとつ前のリンクに移動

TAB
    navi2ch-article-next-link 次のリンクに移動

>
    navi2ch-article-goto-last-message 最後のレスに移動

<
    navi2ch-article-goto-first-message 最初のレスに移動

ESC d
    navi2ch-article-decode-message 記事をデコードする。

ESC i
    navi2ch-article-auto-decode-toggle-text 自動デコードした内容の表示を 切り換える。

v
    navi2ch-article-view-aa アスキーアートを表示 (要 aadisplay)

f
    navi2ch-article-forward-buffer 次のバッファに移動

b
    navi2ch-article-backward-buffer 前のバッファに移動

d
    navi2ch-article-hide-message カーソルのあるレスを隠す・(h のあと) 隠したレスを戻す・($ のあと) レスをブックマークから削除

a
    navi2ch-article-add-important-message カーソルのあるレスをブッ クマークに登録

h
    navi2ch-article-toggle-hide 隠したレスの表示とスレの表示の切り 替え

$
    navi2ch-article-toggle-important スレのブックマークを表示

A
    navi2ch-article-add-global-bookmark スレをグローバルブックマークに登録

C-c C-m
    navi2ch-message-pop-message-buffer 書き込みのとき書き込み画面に 戻る

i
    navi2ch-article-fetch-link リンク先のスレを更新

G
    navi2ch-article-goto-board 指定した板に移動

e
    navi2ch-article-textize-article スレをテキストで保存

?
    navi2ch-article-search レスを検索

C-o
    navi2ch-article-save-dat-file .dat ファイルを保存

F
    navi2ch-article-toggle-message-filter レスに対するフィルタ処理の 有効・無効を切り替える

x
    navi2ch-article-toggle-message-filter カーソルのあるレスに対する レス置換の有効・無効を切り替える

!
    navi2ch-article-add-message-filter-rule レスに対する フィルタ処理の条件を対話的に追加する

C-c C-r
    navi2ch-article-remove-article スレの情報 (取得した .dat ファイルや既読情報など) を消す

u
    navi2ch-article-show-url-at-point カーソルの下の URL を表示し、 キルリングにコピーする。


** A.7 Message モードでのキーバインド

C-c C-c
    navi2ch-message-send-message 書き込みを送信

C-c C-k
    navi2ch-message-exit 書き込みをキャンセル

C-c C-y
    navi2ch-message-cite-original カーソルのあるレスを引用

C-c y
    navi2ch-message-cite-original-from-number 番号で指定したレスを 引用

C-c C-i
    navi2ch-message-insert-backup 前回書いたレスを挿入

C-c C-b
    navi2ch-base64-insert-file ファイルを base64 エンコードして挿入

ESC t
    navi2ch-toggle-offline オフライン・オンラインの切り替え

C-c C-a ?
    navi2ch-message-insert-aa アスキーアートのリストを表示して入力


** A.8 Message モードでのアスキーアート一覧

Message モードで、C-c C-a に続いて下記のキーを押すことで２ちゃん ねる特有のアスキーアートを入力することができる。C-c C-a ? を押す と、アスキーアートのリストを表示することができる。

(ホントは半角カナ (って何ですか?) が使われてるんだけど、色々不都合があ るのでここでは全角ね。)

a
    `(´Д｀)'

b
    `ヽ(`Д´)ノ'

B
    `(((；゜Д゜))ガクガクブルブル'

f
    `( ´_ゝ`)フーン'

e
    `(⊃д`)'

F
    `(´ー｀)'

g
    `(゜Д゜)ゴルァ'

G
    `ガ━━(゜Д゜;)━━ソ!'

h
    `(゜Д゜)ハァ?'

H
    `(;´Д｀)ハァハァ'

i
    `(・∀・)イイ!!'

I
    `(・Ａ・)イクナイ!!'

j
    `(・∀・)ジサクジエンデシタ'

k
    `キタ━━━━━━(゜∀゜)━━━━━━ !!!!!'

K
    `キタ━(゜∀゜)━( ゜∀)━( 　゜)━(　　)━(゜ 　)━(∀゜ )━(゜∀゜)━!!!!'

m
    `(´∀｀)'

M
    `ヽ(´▽｀)ノ'

n
    `(￣ー￣)ニヤリッ'

N
    `(´-`).。ｏＯ(なんでだろう？)'

p
    `（　゜д゜）ポカーン'

s
    `Σ（゜д゜lll）ガーン'

S
    `(´・ω・`)ショボーン'

t
    `y=ー( ゜д゜)・∵.　ターン'

u
    `(゜д゜)ウマー'

U
    `(-＿-)ウツダ'


This document was generated by nawota on March, 23 2011 using texi2html
